### ISSUE TITLE
Problem with Chat Prefix

### ISSUE THREAD

**Issue by bitcruiser77** [beastman3226/BusinessCore#8]
Installed last night, worked fine.  To test, we created a business, hired someone, made a job, and completed the job. Everything was working fine when I first logged in today finish the perms. I used multiverse to teleport to a different world and my business name showed up as a chat prefix. Typed again, the prefix doubled. I deleted the business, did nothing. I deleted the program and jar and restarted.....still there. 

For some reason, my business name appended multiple timesto the prexix on my groupmanager user profile until there were hundreds. I deleted the program and manually removed the prefix and all is good now. Really bummed I can't use this right now as it looks like a nice program that would have been perfect for my small server. If you can think of any fix, I'd love to put this back on. 

I never touched the config or anywhere else for that matter, everything was left as is including prefix set to false. Any idea what would have caused this? If you need more info, let me know. More than happy to list it all out. 

Thanks in advance for all you do. I do appreciate the work you put in.

**Comment by beastman3226** [comment]
Fixed in next update
